# GitHub Pages Configuration
title: AngelEyes Documentation
description: Vision-based focus and posture monitoring assistant using local multimodal AI models
theme: jekyll-theme-minimal

# Optional: Custom domain
# url: "https://yourdomain.com"
# baseurl: "/angeleyes"

# Navigation
navigation:
  - title: Home
    url: /
  - title: GitHub
    url: https://github.com/username/angeleyes
  - title: Issues
    url: https://github.com/username/angeleyes/issues